<?php

require_once("../libraries/fpdf/fpdf.php");

require_once("../process/mail_process.php");

    extract($_REQUEST);

    $formatted_dob = date("d F Y", strtotime($dob));

    $pdf = new FPDF();
    $pdf->AddPage();

    $pdf->SetFillColor(255, 214, 10); // Lighter side of yellow
    $pdf->Rect(0, 0, 210, 297, 'F');

    $pdf->Image('../images/png/logo-no-background.png', 60, 20, 90);

    $pdf->Rect(15, 15, 170, 260, 5, 'DF');
    $pdf->SetDrawColor(160, 160, 160);

    $pdf->SetFont('Arial', 'BU', 20);
    $pdf->SetTextColor(33, 37, 41); // Bootstrap text-dark
    $pdf->Ln(70);
    $pdf->Cell(0, 20, 'User Registration Details', 0, 1, 'C');


    $pdf->SetX(55);
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->setTextcolor(255,255,255); // White color
    $pdf->SetFillColor(0, 0, 0); // Black color

    $pdf->SetLineWidth(0);
    $pdf->Cell(32, 6, "Name", 1, 0, 'C',true);
    $pdf->SetFillColor(224, 224, 224); // Light Grey color
    $pdf->setTextcolor(0,0,0);
    $pdf->Cell(70, 6, $name, 1, 1, 'C',true);


    $pdf->SetX(55);
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->setTextcolor(255,255,255); // White color
    $pdf->SetFillColor(0, 0, 0); // Black color

    $pdf->SetLineWidth(0);
    $pdf->Cell(32, 6, "Email", 1, 0, 'C',true);
    $pdf->SetFillColor(224, 224, 224); // Light Grey color
    $pdf->setTextcolor(0,0,0);
    $pdf->Cell(70, 6, $email, 1, 1, 'C',true);


    $pdf->SetX(55);
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->setTextcolor(255,255,255); // White color
    $pdf->SetFillColor(0, 0, 0); // Black color

    $pdf->SetLineWidth(0);
    $pdf->Cell(32, 6, "Password", 1, 0, 'C',true);
    $pdf->SetFillColor(224, 224, 224); // Light Grey color
    $pdf->setTextcolor(0,0,0);
    $pdf->Cell(70, 6, $password, 1, 1, 'C',true);


    $pdf->SetX(55);
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->setTextcolor(255,255,255); // White color
    $pdf->SetFillColor(0, 0, 0); // Black color

    $pdf->SetLineWidth(0);
    $pdf->Cell(32, 6, "Gender", 1, 0, 'C',true);
    $pdf->SetFillColor(224, 224, 224); // Light Grey color
    $pdf->setTextcolor(0,0,0);
    $pdf->Cell(70, 6, $gender, 1, 1, 'C',true);

    $pdf->SetX(55);
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->setTextcolor(255,255,255); // White color
    $pdf->SetFillColor(0, 0, 0); // Black color

    $pdf->SetLineWidth(0);
    $pdf->Cell(32, 6, "Date Of Birth", 1, 0, 'C',true);
    $pdf->SetFillColor(224, 224, 224); // Light Grey color
    $pdf->setTextcolor(0,0,0);
    $pdf->Cell(70, 6, $formatted_dob, 1, 1, 'C',true);


    $pdf->Ln(130);
    $pdf->SetFont('Arial', 'BI', 10);
    $pdf->SetTextColor(108, 117, 125);
    $pdf->Cell(0,10,'Generated by Admin Panel @ BlogBeat Copyright ' . date('Y'), 0,0, 'C');

    
    $filename = 'credentials_' . time() . '.pdf';
    $filepath = 'user_reports/' . $filename;
    
    $pdf->Output("F", $filepath);
    

    registeration_mail($name, $email);
    $message = urlencode("Registration Successful, Please wait for admin approval. You can download your credentials here: <a href='pdf/$filepath' download>Download PDF</a>");

    header("Location: ../login.php?register=success&message=$message&color=alert-success");
    exit();

?>
